#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

random_secret() {
  openssl rand -hex 32
}

cd "${REPO_ROOT}"

command -v openssl >/dev/null 2>&1 || die "openssl is required to generate secrets."

if [[ -f "${ENV_FILE}" ]]; then
  echo ".env already exists; leaving it unchanged."
  exit 0
fi

umask 077
cat > "${ENV_FILE}" <<EOF
# Ubuntu Desktop deployment environment.
# Generated by scripts/bootstrap-env.sh. Do not commit real secrets.

COMPOSE_PROJECT_NAME=policy-rag

POSTGRES_PASSWORD=$(random_secret)
POSTGRES_HOST_BIND=127.0.0.1
POSTGRES_HOST_PORT=5432

REDIS_HOST_BIND=127.0.0.1
REDIS_HOST_PORT=6379

QDRANT_HOST_BIND=127.0.0.1
QDRANT_HOST_PORT=6334
QDRANT_COLLECTION=company_policies_structural
QDRANT_MEMORY_COLLECTION=user_memories

BACKEND_HOST_BIND=127.0.0.1
BACKEND_HOST_PORT=8000

FRONTEND_HOST_BIND=0.0.0.0
FRONTEND_HOST_PORT=8080

JWT_ACCESS_SECRET=$(random_secret)
JWT_REFRESH_SECRET=$(random_secret)

SEED_DEFAULT_USER=false
DEFAULT_USER_LOGIN=admin@example.com
DEFAULT_USER_PASSWORD=replace-before-enabling-seed
DEFAULT_USER_DISPLAY_NAME=Admin

REFRESH_COOKIE_SECURE=false
REFRESH_COOKIE_SAMESITE=lax

EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
OLLAMA_MODEL=hf.co/microsoft/Phi-3-mini-4k-instruct-gguf
OLLAMA_NUM_PREDICT=256
OLLAMA_KEEP_ALIVE=30m
WARM_METADATA_ON_STARTUP=false
PROMPT_CONTEXT_MAX_CHARS=2800
PROMPT_MIN_SOURCES=3
PROMPT_MAX_SOURCES=4
EMBEDDING_CACHE_SIZE=256

HF_HUB_DISABLE_XET=1
EOF

chmod 600 "${ENV_FILE}"
mkdir -p "${REPO_ROOT}/policies" "${REPO_ROOT}/qdrant_data"

echo "Created ${ENV_FILE}"
